# Generated by Django 3.2.7 on 2021-11-14 13:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wish',
            field=models.ManyToManyField(blank=True, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
