# Generated by Django 3.2.8 on 2021-11-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawa', '0002_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='instagram_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='kakao_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
